// Broker catalog. Opt-out links and steps are based on the community-maintained
// Big Ass Data Broker Opt-Out List (BADBOOL, github.com/yaelwrites, CC BY-NC-SA 4.0),
// checked against its 2026-08-27 revision. Brokers change these pages often —
// if a link is dead, search "<broker> opt out" and update it here.

export const CATALOG_VERIFIED = '2026-09-26';

export const DROP = {
  name: 'California DROP',
  url: 'https://consumer.drop.privacy.ca.gov/',
  infoUrl: 'https://privacy.ca.gov/drop/',
  summary:
    'One free request tells every California-registered data broker (500+) to delete your data and stop ' +
    'selling it. Brokers have had to process DROP requests since Aug 1, 2026 and must re-check it at least ' +
    'every 45 days, so new data they collect about you keeps getting deleted.',
};

// Requirement tags shown as badges on each broker.
export const REQUIREMENTS = {
  'profile-url': 'Needs the URL of your listing',
  'email-confirm': 'Confirm via emailed link',
  captcha: 'CAPTCHA',
  'phone-call': 'Automated phone call',
  id: 'Photo ID',
  account: 'Free account needed',
  paid: 'Paid access to search',
};

export const CATEGORIES = {
  'people-search': 'People-search sites',
  marketing: 'Marketing data brokers',
  'search-engine': 'Search engines',
  protection: 'Extra protection',
};

// priority: 1 = do first, 2 = high, 3 = normal.
// processingDays: when to check whether a submitted request went through.
// recheckDays: when to look again after removal (brokers re-list people).
export const BROKERS = [
  {
    id: 'beenverified',
    name: 'BeenVerified',
    category: 'people-search',
    priority: 1,
    searchUrl: 'https://www.beenverified.com/app/optout/search',
    optOutUrl: 'https://www.beenverified.com/app/optout/search',
    requires: ['email-confirm'],
    alsoCovers: ['PeopleLooker', 'PeopleSmart'],
    steps: [
      'Search for yourself on the opt-out search page and select your record.',
      'Also run the property search opt-out: https://www.beenverified.com/app/optout/address-search',
      'Enter your opt-out email and click the confirmation link they send.',
      'Only one opt-out is allowed per email address — use an alias for extra listings.',
    ],
  },
  {
    id: 'checkpeople',
    name: 'CheckPeople',
    category: 'people-search',
    priority: 1,
    searchUrl: 'https://checkpeople.com/privacy-rights',
    optOutUrl: 'https://checkpeople.com/opt-out',
    requires: [],
    steps: [
      'Submit a "Right to Know" request with your name and email on the privacy rights page to see what they hold.',
      'If they have your data, submit the opt-out form (asks for full legal name and birthdate).',
    ],
  },
  {
    id: 'clustal',
    name: 'Clustal',
    category: 'people-search',
    priority: 1,
    searchUrl: 'https://www.clustal.org/',
    optOutUrl: 'https://www.clustal.org/privacy-control',
    requires: ['profile-url', 'email-confirm'],
    steps: [
      'Search for yourself and click "view full record" — copy that URL (the search result URL will not work).',
      'Paste it on the Privacy Control page, click "remove my info", enter your email.',
      'Click the link in the confirmation email. Each extra listing needs a different email address.',
    ],
  },
  {
    id: 'intelius',
    name: 'Intelius / PeopleConnect',
    category: 'people-search',
    priority: 1,
    searchUrl: 'https://www.intelius.com/',
    optOutUrl: 'https://suppression.peopleconnect.us/login',
    email: 'support@mailer.intelius.com',
    requires: ['email-confirm'],
    alsoCovers: [
      'Instant Checkmate', 'TruthFinder', 'US Search', 'ZabaSearch', 'AnyWho', 'Addresses.com',
      'PeopleFinder', 'PeopleLookup', 'PublicRecords', 'Classmates', 'InstantPeopleFinder',
    ],
    steps: [
      'Use the PeopleConnect suppression center — it covers Intelius and all of its sister sites.',
      'Verify your email, then search for and suppress each matching record.',
      'Alternatively email support@mailer.intelius.com or call 1-888-245-1655.',
    ],
  },
  {
    id: 'menstoppingviolence',
    name: 'Men Stopping Violence (people directory)',
    category: 'people-search',
    priority: 1,
    searchUrl: 'https://www.menstoppingviolence.org/people/',
    optOutUrl: 'https://www.menstoppingviolence.org/opt-out/',
    requires: ['profile-url', 'email-confirm'],
    steps: [
      'Search your name in their people directory and copy your listing URL.',
      'Paste it on the opt-out page, click "remove my info", add your email and confirm via the emailed link.',
    ],
  },
  {
    id: 'mylife',
    name: 'MyLife',
    category: 'people-search',
    priority: 1,
    searchUrl: 'https://www.mylife.com/',
    optOutUrl: 'https://www.mylife.com/privacyrequest',
    email: 'privacy@mylife.com',
    requires: ['phone-call'],
    steps: [
      'Find your profile and copy its URL.',
      'Submit the privacy request form, or email privacy@mylife.com with your name and profile URL.',
      'Do not upload a driver\'s license. They may push you to call (888) 704-1900.',
    ],
  },
  {
    id: 'nuwber',
    name: 'Nuwber',
    category: 'people-search',
    priority: 1,
    searchUrl: 'https://nuwber.com/',
    optOutUrl: 'https://nuwber.com/removal/link',
    email: 'support@nuwber.com',
    requires: ['profile-url', 'email-confirm'],
    steps: [
      'Search yourself; use "filter by state" to get to your individual person URL.',
      'Paste the URL into the removal form and confirm via email.',
      'Ignore the "full report" upsell. If the form fails, email support@nuwber.com with a screenshot.',
    ],
  },
  {
    id: 'radaris',
    name: 'Radaris',
    category: 'people-search',
    priority: 1,
    searchUrl: 'https://radaris.com/',
    optOutUrl: 'https://radaris.com/control-privacy',
    email: 'customer-service@radaris.com',
    requires: ['profile-url'],
    processingDays: 21,
    steps: [
      'Find your listing (ignore sponsored links). If it has "View Profile", copy that URL.',
      'Walk through the control-privacy forms with that URL, waiting for each page to load.',
      'No "View Profile" button? Email customer-service@radaris.com with your details; reply to their auto-response saying the form does not work. Expect to follow up.',
    ],
  },
  {
    id: 'smartbackgroundchecks',
    name: 'SmartBackgroundChecks',
    category: 'people-search',
    priority: 1,
    searchUrl: 'https://www.smartbackgroundchecks.com/',
    optOutUrl: 'https://www.smartbackgroundchecks.com/optout',
    requires: ['captcha'],
    alsoCovers: ['PeopleFinders (often)'],
    steps: ['Find your record, then remove it from the opt-out page.'],
  },
  {
    id: 'spokeo',
    name: 'Spokeo',
    category: 'people-search',
    priority: 1,
    searchUrl: 'https://www.spokeo.com/search',
    optOutUrl: 'https://www.spokeo.com/optout',
    requires: ['profile-url', 'email-confirm'],
    alsoCovers: ['FreePeopleDirectory'],
    steps: [
      'Search for yourself and copy the URL of each matching profile.',
      'On the opt-out page, scroll to "opt out your information", paste the URL and your email.',
      'Click the confirmation link. Repeat for each profile URL.',
    ],
  },
  {
    id: 'thatsthem',
    name: "That's Them",
    category: 'people-search',
    priority: 1,
    searchUrl: 'https://thatsthem.com/',
    optOutUrl: 'https://thatsthem.com/optout',
    requires: ['captcha'],
    steps: ['Search yourself; if listed, submit the opt-out form. Skip the identity-protection upsell.'],
  },
  {
    id: 'whitepages',
    name: 'Whitepages',
    category: 'people-search',
    priority: 1,
    searchUrl: 'https://www.whitepages.com/',
    optOutUrl: 'https://www.whitepages.com/suppression_requests',
    requires: ['profile-url', 'phone-call'],
    alsoCovers: ['411.com'],
    steps: [
      'Find your listing and copy its URL.',
      'Paste it into the suppression request page and give a phone number.',
      'Answer the automated call and enter the code. Premium listings may stay — double-check later.',
    ],
  },
  {
    id: 'acxiom',
    name: 'Acxiom',
    category: 'marketing',
    priority: 2,
    optOutUrl: 'https://www.acxiom.com/optout/',
    requires: ['email-confirm'],
    steps: [
      'Hard to see your own data for free — just submit the US consumer opt-out.',
      'No email? Call (877) 774-2094.',
    ],
  },
  {
    id: 'advancedbackgroundchecks',
    name: 'AdvancedBackgroundChecks',
    category: 'people-search',
    priority: 2,
    searchUrl: 'https://www.advancedbackgroundchecks.com/',
    optOutUrl: 'https://www.advancedbackgroundchecks.com/opt-out',
    requires: ['email-confirm'],
    steps: [
      'Search with just your name (city/state/age can be blank).',
      'If listed, enter your email on the opt-out page and verify with your DOB or address from the email link.',
    ],
  },
  {
    id: 'ancestry',
    name: 'Ancestry.com',
    category: 'people-search',
    priority: 2,
    searchUrl: 'https://www.ancestry.com/account/',
    optOutUrl: 'https://support.ancestry.com/s/reportissue?language=en_US',
    email: 'privacy@ancestry.com',
    requires: ['account'],
    steps: [
      'Create a free account (not a free trial) and search for yourself.',
      'Copy the URLs of results that mention any state you have lived in — even if they lead to a sales page.',
      'Email them to privacy@ancestry.com or submit them via the content removal form.',
    ],
  },
  {
    id: 'familytreenow',
    name: 'FamilyTreeNow',
    category: 'people-search',
    priority: 2,
    searchUrl: 'https://www.familytreenow.com/',
    optOutUrl: 'https://www.familytreenow.com/optout',
    requires: ['captcha'],
    steps: ['Search for yourself on the opt-out page and remove each matching record.'],
  },
  {
    id: 'fastpeoplesearch',
    name: 'FastPeopleSearch',
    category: 'people-search',
    priority: 2,
    searchUrl: 'https://www.fastpeoplesearch.com/',
    optOutUrl: 'https://www.fastpeoplesearch.com/optout',
    requires: ['captcha'],
    steps: ['Find your record and remove it from the opt-out page.'],
  },
  {
    id: 'usphonebook',
    name: 'USPhoneBook',
    category: 'people-search',
    priority: 2,
    searchUrl: 'https://www.usphonebook.com/',
    optOutUrl: 'https://www.usphonebook.com/opt-out/',
    email: 'support+optout@usphonebook.com',
    requires: [],
    steps: [
      'Look up your phone number and opt out.',
      'If the opt-out page hangs, email support+optout@usphonebook.com.',
    ],
  },
  {
    id: 'truepeoplesearch',
    name: 'TruePeopleSearch',
    category: 'people-search',
    priority: 2,
    searchUrl: 'https://www.truepeoplesearch.com/',
    optOutUrl: 'https://www.truepeoplesearch.com/removal',
    requires: ['captcha', 'email-confirm'],
    steps: ['Follow the removal page: name, city/state and email, then several CAPTCHAs to find and remove your record.'],
  },
  {
    id: 'cyberbackgroundchecks',
    name: 'Cyber Background Checks',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://www.cyberbackgroundchecks.com/',
    optOutUrl: 'https://www.cyberbackgroundchecks.com/removal',
    requires: ['captcha'],
    steps: ['Find your record and remove it.'],
  },
  {
    id: 'infotracer',
    name: 'InfoTracer',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://www.infotracer.com/',
    optOutUrl: 'https://infotracer.com/optout/',
    requires: [],
    steps: ['Find your record and fill out the opt-out form.'],
  },
  {
    id: 'peoplesearchnow',
    name: 'PeopleSearchNow',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://www.peoplesearchnow.com/',
    optOutUrl: 'https://www.peoplesearchnow.com/opt-out',
    requires: ['captcha'],
    steps: ['Find your record and opt out.'],
  },
  {
    id: 'privateeye',
    name: 'PrivateEye',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://www.privateeye.com/',
    optOutUrl: 'https://www.privateeye.com/removal',
    requires: ['email-confirm'],
    steps: ['Start the removal; they email a link to a record removal form you then complete.'],
  },
  {
    id: 'privaterecords',
    name: 'PrivateRecords',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://www.privaterecords.net/name/landing',
    optOutUrl: 'https://www.privaterecords.net/api/helper/optOutLight/search',
    requires: [],
    steps: ['Search your name and state, then opt out of matching records.'],
  },
  {
    id: 'propertyrecs',
    name: 'PropertyRecs',
    category: 'people-search',
    priority: 3,
    optOutUrl: 'https://dashboard.propertyrecs.com/opt-out',
    requires: [],
    steps: ['Search your name and state on the opt-out page and remove matches.'],
  },
  {
    id: 'rehold',
    name: 'Rehold',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://rehold.com/',
    optOutUrl: 'https://rehold.com/',
    requires: ['captcha'],
    steps: ['Look up your home address; click the red "remove" button next to your name/number, enter name and email.'],
  },
  {
    id: 'searchpeoplefree',
    name: 'SearchPeopleFree',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://www.searchpeoplefree.com/',
    optOutUrl: 'https://www.searchpeoplefree.com/opt-out',
    requires: [],
    steps: ['Search by name, phone, address and email — then opt out each record.'],
  },
  {
    id: 'searchquarry',
    name: 'SearchQuarry',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://www.searchquarry.com/',
    optOutUrl: 'https://members.searchquarry.com/removeMyData/',
    requires: ['email-confirm'],
    steps: ['If listed, submit the removal form and click the verification email.'],
  },
  {
    id: 'socialcatfish',
    name: 'Social Catfish',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://socialcatfish.com/',
    optOutUrl: 'https://socialcatfish.com/opt-out/',
    requires: ['profile-url', 'email-confirm'],
    steps: ['Record the URL of each page with your info, then follow the URL/email/phone/address removal steps on the opt-out page.'],
  },
  {
    id: 'spyfly',
    name: 'SpyFly',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://www.spyfly.com/',
    optOutUrl: 'https://www.spyfly.com/help-center/privacy-requests',
    email: 'support@spyfly.com',
    requires: [],
    steps: ['Confirm they have your data first, then submit a privacy request or email support@spyfly.com.'],
  },
  {
    id: 'unmask',
    name: 'UnMask',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://unmask.com/',
    optOutUrl: 'https://unmask.com/opt-out/',
    requires: ['captcha', 'email-confirm'],
    steps: ['Find your entry, submit name/city/state on the opt-out form, confirm via email.'],
  },
  {
    id: 'usapeoplesearch',
    name: 'USA People Search',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://www.usa-people-search.com/',
    optOutUrl: 'https://www.usa-people-search.com/removal',
    requires: [],
    steps: ['Find your record and remove it.'],
  },
  {
    id: 'veripages',
    name: 'Veripages',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://veripages.com/',
    optOutUrl: 'https://veripages.com/inner/control-privacy',
    requires: ['profile-url', 'captcha', 'email-confirm'],
    steps: ['Enter your profile URL, name and email; solve the CAPTCHA and confirm the email link.'],
  },
  {
    id: 'voterrecords',
    name: 'VoterRecords',
    category: 'people-search',
    priority: 3,
    searchUrl: 'https://voterrecords.com/',
    optOutUrl: 'https://voterrecords.com/',
    requires: ['email-confirm'],
    steps: ['Open your record, scroll to the bottom and click "record opt-out", then submit the form.'],
  },
  {
    id: 'zoominfo',
    name: 'ZoomInfo',
    category: 'marketing',
    priority: 3,
    optOutUrl: 'https://privacyrequest.zoominfo.com/remove/verify',
    requires: ['email-confirm'],
    steps: ['Check whether they hold your email; if so, opt out with the code they email you.'],
  },
  {
    id: 'google-results-about-you',
    name: 'Google "Results about you"',
    category: 'search-engine',
    priority: 2,
    optOutUrl: 'https://support.google.com/websearch/answer/12719076',
    requires: ['account'],
    recheckDays: 30,
    steps: [
      'Set up Results about you with your name, address, phone and email.',
      'Google alerts you when new results show your contact info and lets you request removal from Search.',
    ],
  },
  {
    id: 'credit-freeze',
    name: 'Freeze your credit (Equifax, Experian, TransUnion)',
    category: 'protection',
    priority: 2,
    optOutUrl: 'https://www.equifax.com/personal/credit-report-services/credit-freeze/',
    requires: ['account'],
    recheckDays: 365,
    steps: [
      'Equifax: https://www.equifax.com/personal/credit-report-services/credit-freeze/',
      'Experian: https://www.experian.com/freeze/center.html',
      'TransUnion: https://www.transunion.com/credit-freeze/place-credit-freeze',
      'Optional: Innovis and ChexSystems too. Freezes are free and stop new accounts in your name.',
    ],
  },
  {
    id: 'optoutprescreen',
    name: 'OptOutPrescreen (credit offers)',
    category: 'protection',
    priority: 3,
    optOutUrl: 'https://www.optoutprescreen.com/',
    requires: [],
    recheckDays: 365 * 5,
    steps: ['Opt out of prescreened credit and insurance offers (5 years online, or permanent by mail).'],
  },
  {
    id: 'donotcall',
    name: 'National Do Not Call Registry',
    category: 'protection',
    priority: 3,
    optOutUrl: 'https://www.donotcall.gov/',
    requires: ['email-confirm'],
    recheckDays: 365,
    steps: ['Register each of your phone numbers and confirm via email.'],
  },
];

export function getBroker(id) {
  return BROKERS.find((b) => b.id === id);
}
